

export const GET_TODO_LIST = 'GET_TODO_LIST';
export const GET_TODO_LIST_SUCCEEDED = 'GET_TODO_LIST_SUCCEEDED';
export const GET_TODO_LIST_FAILED = 'GET_TODO_LIST_FAILED';

export const GET_ONE_TODO = 'GET_ONE_TODO';
export const GET_ONE_TODO_SUCCEEDED = 'GET_ONE_TODO_SUCCEEDED';
export const GET_ONE_TODO_FAILED = 'GET_ONE_TODO_FAILED';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_SUCCEEDED = 'UPDATE_TODO_SUCCEEDED';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_TODO_SUCCEEDED = 'DELETE_TODO_SUCCEEDED';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';


